version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redisdb
    environment:
      - REDIS_HOST=redisdb
      - REDIS_PORT=6379

  redisdb:
    image: redis
    ports:
      - "6379"
    volumes:
      - redis_data:/data

volumes:
    redis_data:
