apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    app: dale
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
          protocol: TCP
      env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
