apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: dale
spec:
  containers:
    - name: web
      image: dbastos/dale-slack:4
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
