apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: dale
spec:
  containers:
    - name: web
      image: dbastos/dale-slack:3
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
